"""Controlled vocabularies used across the canonical schemas."""

from __future__ import annotations

from enum import Enum

__all__ = [
    "SourceType",
    "SourceTier",
    "EvidenceCluster",
    "EventStatus",
    "ConfirmationStatus",
    "AlertLevel",
    "SignalFamily",
    "DataRealism",
    "HostCategory",
]


class StrEnum(str, Enum):
    """``str``-valued enum so values serialise transparently to JSON/Parquet."""

    def __str__(self) -> str:  # pragma: no cover - trivial
        return str(self.value)


class SourceType(StrEnum):
    """What kind of observation process produced the record."""

    OFFICIAL = "official"                # WAHIS immediate notifications / follow-ups
    OFFICIAL_DERIVED = "official_derived"  # EMPRES-i republishing WAHIS
    MEDIA = "media"                      # GDELT, PADI-web, ProMED, HealthMap
    AGGREGATOR = "aggregator"            # BEACON, EIOS (ingest media + official)
    ENVIRONMENTAL = "environmental"      # ERA5, ERA5-Land, WorldClim
    EXPOSURE = "exposure"                # GLW4 livestock density
    CONTEXTUAL = "contextual"            # FAOSTAT socio-economic denominators


class SourceTier(StrEnum):
    """Epistemic standing of a source in the evidence hierarchy."""

    PRIMARY_OFFICIAL = "primary_official"   # the reference observation process
    SECONDARY_OFFICIAL = "secondary_official"  # downstream of a primary source
    INTELLIGENCE = "intelligence"           # unverified / signal-level
    COVARIATE = "covariate"                 # not an observation of disease at all


class EvidenceCluster(StrEnum):
    """Dependence groups (see ``config/config.yaml: independence.clusters``)."""

    OFFICIAL = "official"
    MEDIA = "media"
    AGGREGATOR = "aggregator"
    ENVIRONMENTAL = "environmental"
    EXPOSURE = "exposure"
    UNKNOWN = "unknown"


class EventStatus(StrEnum):
    """Lifecycle of an official event record."""

    SUSPECTED = "suspected"
    CONFIRMED = "confirmed"
    RESOLVED = "resolved"
    ONGOING = "ongoing"
    DENIED = "denied"
    UNKNOWN = "unknown"


class ConfirmationStatus(StrEnum):
    """How strongly the record asserts that disease was actually present."""

    LABORATORY_CONFIRMED = "laboratory_confirmed"
    CLINICALLY_SUSPECTED = "clinically_suspected"
    UNVERIFIED_SIGNAL = "unverified_signal"
    RUMOUR = "rumour"
    NOT_APPLICABLE = "not_applicable"


class AlertLevel(StrEnum):
    """Operational alert bands (thresholds in ``config/thresholds.yaml``)."""

    NONE = "NONE"
    INFO = "INFO"
    WATCH = "WATCH"
    ALERT = "ALERT"
    CRITICAL = "CRITICAL"

    @property
    def rank(self) -> int:
        order = {"NONE": 0, "INFO": 1, "WATCH": 2, "ALERT": 3, "CRITICAL": 4}
        return order[self.value]


class SignalFamily(StrEnum):
    """Families of evidence entering the early-warning fusion.

    Counterfactual ablation operates on exactly these families, so they must
    partition the feature space.
    """

    TEMPORAL_ANOMALY = "temporal_anomaly"
    SPATIAL_RISK = "spatial_risk"
    ENVIRONMENTAL = "environmental"
    EXPOSURE = "livestock_exposure"
    INTELLIGENCE = "intelligence"
    HISTORICAL_BASELINE = "historical_baseline"
    REPORTING_BEHAVIOUR = "reporting_behaviour"


class DataRealism(StrEnum):
    """Explicit labelling of how real a record is. Never silently defaults."""

    REAL = "real"              # fetched from the actual source
    SYNTHETIC = "synthetic"    # generated by src/ingestion/sample_generator.py
    MOCK = "mock"              # hand-shaped stand-in for an inaccessible API
    DERIVED = "derived"        # computed from other records in this repository


class HostCategory(StrEnum):
    DOMESTIC = "domestic"
    WILD = "wild"
    MIXED = "mixed"
    UNKNOWN = "unknown"
